{
    "NAME": "**Server name:** {{NAME}}",
    "OWNER": "**Owner:** {{OWNER}}",
    "ID": "**Server ID:** {{ID}}",
    "CREATED": "**Created At:** {{CREATED}}",
    "REGION": "Server region:",
    "VERIFICATION": "**Verification level:** {{LEVEL}}",
    "PARTNER": "**Partner:** {{PARTNER}}",
    "YES": "Partnered",
    "NO": "Not partnered",
    "MEMBER": "**Membercount:** {{NUMBER}}",
    "PREMIUM": "**Nitro Boost:** Level **{{NUMBER}}**,",
    "BOOSTS": "with **{{BOOSTS}}** Boosts",
    "FEATURES": "**Features:**",
    "ROLES": "Roles ({{NUMBER}})",
    "SHARD_ID": "**Shard ID:** {{ID}}",
    "TEXT": "**Text:** {{NUMBER}",
    "VOICE": "**Voice:** {{NUMBER}}",
    "CATEGORY": "**Categories:** {{NUMBER}}",
    "CHANNELS": "Channels ({{NUMBER}})",
    "FOOTER": "Requested by: {{USER}}"
}